# Generated by Django 4.2.7 on 2025-10-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('favorite_movies', models.ManyToManyField(blank=True, related_name='favorited_by', to='movies.movie', verbose_name='Избранные фильмы')),
                ('favorite_series', models.ManyToManyField(blank=True, related_name='favorited_by', to='movies.series', verbose_name='Избранные сериалы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('watchlist_movies', models.ManyToManyField(blank=True, related_name='in_watchlist', to='movies.movie', verbose_name='Список к просмотру (фильмы)')),
                ('watchlist_series', models.ManyToManyField(blank=True, related_name='in_watchlist', to='movies.series', verbose_name='Список к просмотру (сериалы)')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view', 'Просмотр'), ('rating', 'Оценка'), ('comment', 'Комментарий'), ('favorite', 'Добавление в избранное')], max_length=20, verbose_name='Тип активности')),
                ('content_type', models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('news', 'Новость')], max_length=20, verbose_name='Тип контента')),
                ('content_id', models.IntegerField(verbose_name='ID контента')),
                ('content_title', models.CharField(max_length=300, verbose_name='Название контента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активности пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
