# Generated by Django 4.2.7 on 2025-10-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_episode_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(verbose_name='Номер эпизода'),
        ),
    ]
