# Generated by Django 4.2.7 on 2025-10-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_episode_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.PositiveIntegerField(verbose_name='Номер сезона'),
        ),
    ]
