# Generated by Django 4.2.7 on 2025-10-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_season_season_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
    ]
