# Generated by Django 4.2.7 on 2025-10-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_unique_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_az'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name_az'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AddField(
            model_name='country',
            name='name_az',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (AZ)'),
        ),
        migrations.AddField(
            model_name='episode',
            name='description_az',
            field=models.TextField(blank=True, verbose_name='Описание (AZ)'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (AZ)'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_az',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (AZ)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_az',
            field=models.TextField(blank=True, verbose_name='Описание (AZ)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_az',
            field=models.CharField(blank=True, max_length=300, verbose_name='Название (AZ)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_az',
            field=models.TextField(blank=True, verbose_name='Содержание (AZ)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок (AZ)'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_az',
            field=models.TextField(blank=True, verbose_name='Биография (AZ)'),
        ),
        migrations.AddField(
            model_name='season',
            name='description_az',
            field=models.TextField(blank=True, verbose_name='Описание (AZ)'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (AZ)'),
        ),
        migrations.AddField(
            model_name='series',
            name='description_az',
            field=models.TextField(blank=True, verbose_name='Описание (AZ)'),
        ),
        migrations.AddField(
            model_name='series',
            name='title_az',
            field=models.CharField(blank=True, max_length=300, verbose_name='Название (AZ)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_az',
            field=models.TextField(blank=True, verbose_name='Содержание (AZ)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (AZ)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=100, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title_uz',
            field=models.CharField(max_length=200, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_uz',
            field=models.CharField(max_length=300, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=models.TextField(verbose_name='Содержание (UZ)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=300, verbose_name='Заголовок (UZ)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio_uz',
            field=models.TextField(blank=True, verbose_name='Биография (UZ)'),
        ),
        migrations.AlterField(
            model_name='season',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title_uz',
            field=models.CharField(max_length=300, verbose_name='Название (UZ)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content_uz',
            field=models.TextField(verbose_name='Содержание (UZ)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title_uz',
            field=models.CharField(max_length=200, verbose_name='Заголовок (UZ)'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'season_number')},
        ),
    ]
