# Generated by Django 4.2.7 on 2025-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_country_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='movies.country', verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='movies.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='series',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='movies.country', verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='movies.genre', verbose_name='Жанры'),
        ),
    ]
